---
dependency:
  name: galaxy
driver:
  name: libvirt
platforms:
  - name: instance
    image_url: "file:///home/zedr/dist/centos/CentOS-Stream-GenericCloud-8-20210603.0.x86_64.qcow2"
    ##image_url: https://cloud.centos.org/centos/8-stream/x86_64/images/CentOS-Stream-GenericCloud-8-20210603.0.x86_64.qcow2
provisioner:
  name: ansible
verifier:
  name: ansible
