---
- name: "Create a network for the application"
  containers.podman.podman_network:
    name: "net-{{ http_port }}"
    internal: true

- name: "Set common Pod state to: {{ pod_state }}"
  containers.podman.podman_pod:
    name: "pod-{{ http_port }}"
    hostname: "pod-{{ http_port }}"
    state: "{{ pod_state }}"
    network: "net-{{ http_port }}"
