---
- name: "Create the Wordpress WWW volume"
  become_user: "{{ podman_user }}"
  become: true
  containers.podman.podman_volume:
    name: "wordpress-{{ http_port }}-www"
    state: "present"

- name: "Set the Wordpress container state to: {{ pod_state }}"
  become_user: "{{ podman_user }}"
  become: true
  containers.podman.podman_container:
    name: "wordpress-{{ http_port }}"
    pod: "pod-{{ http_port }}"
    restart_policy: on-failure
    image: "docker.io/library/wordpress:5.6.2-php7.4"
    privileged: false
    volumes:
      - "wordpress-{{ http_port }}-www:/var/www/html"
    env:
      WORDPRESS_DB_HOST: "127.1"
      WORDPRESS_DB_USER: "{{ mysql_user }}"
      WORDPRESS_DB_PASSWORD: "{{ mysql_pass }}"
      WORDPRESS_DB_NAME: "wordpress"
